
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BereketBabiso/Config-Server1/tree/master/config-server
          #username: 
          #password: 
          search-paths:
          - '*'